from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

# ESSA LINHA DIZ AO COMFYUI PARA PROCURAR O JS NA RAIZ DO SEU NODE
WEB_DIRECTORY = "."

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']